# Generated by Django 5.1.4 on 2025-01-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('value', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('Email', 'Email Address'), ('Phone', 'Contact Phone'), ('Address', 'Post Address'), ('Operations', 'Opening Hours')], default='Email', max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
