# Generated by Django 5.1.4 on 2025-01-24 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Dry Cleaning', 'Dry Cleaning'), ('Steam Ironing', 'Steam Ironing'), ('Wash & Iron', 'Wash & Iron'), ('Garments', 'Garments')], default='Dry Cleaning', help_text='Something like Ironing, drying etc', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200, unique=True)),
                ('price', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_pricing', to='core.service')),
            ],
        ),
    ]
